### ISSUE TITLE
brew install --HEAD kops fails (sha1sum command is not available)

### ISSUE THREAD

**Issue by tcf909** [kubernetes/kops#1999]
When trying to install (or upgrade) kops using brew I get:

"sha1sum command is not available" but I clearly have it installed on my system. This is a recent problem, as I have used --HEAD for awhile.

```
Cs-MacBook-Pro:~ tc.ferguson$ brew install --HEAD kops
==> Using the sandbox
==> Cloning https://github.com/kubernetes/kops.git
Updating /Users/tc.ferguson/Library/Caches/Homebrew/kops--git
==> Checking out branch master
==> make -C /private/tmp/kops-20170224-17169-h5ixtu/src/k8s.io/kops
Last 15 lines from /Users/tc.ferguson/Library/Logs/Homebrew/kops/01.make:
2017-02-24 22:09:19 -0800

make
-C
/private/tmp/kops-20170224-17169-h5ixtu/src/k8s.io/kops

Makefile:70: *** "sha1sum command is not available (on MacOS try 'brew install md5sha1sum')".  Stop.

READ THIS: http://docs.brew.sh/Troubleshooting.html

TCs-MacBook-Pro:~ tc.ferguson$ sha1sum --help
Usage: sha1sum [<option>] <file> [<file> [...] ]
       sha1sum [<option>] --check <file>

Note:  These options are mostly compatible with GNU md5sum
       -s, -h, and -V are not available in GNU md5sum

 -b, --binary         Read files in binary mode
 -c, --check <file>   Check MD5 sums from <file>
 -t, --text           Read files in ASCII mode

 -s, --status         Silent mode: Use exit code to determine verification

 -h, --help           Display this help message and exit
 -V, --version        Display program version and exit
```

**Comment by geojaz** [comment]
@tcf909 I just checked this out on my system to verify, but you're correct. I also tried pulling from GitHub master directly and it's also broken. I thought we fixed this one! 

I am looking into a fix, but in the meantime if you need to install kops from HEAD and your system allows it, `brew install md5sha1sum` will install the utility that you need to compile. Sorry for your trouble and we will get this one fixed right up!

**Comment by geojaz** [comment]
We tried to make changes to the brew formula to fix this, but it looks like you don't have the latest version of the formula available. I'm not exactly sure how homebrew works, maybe we need to push the latest changes to brew or something. 

In the meantime, you can either `brew install md5sha1sum` and then `brew install kops` or you can `brew edit kops` and adjust your dependency section as follows. If you continue to have difficulties, please join us in #kops in the k8s slack and we'll help you debug.

```
...
depends_on "go" => :build
depends_on "kubernetes-cli"
depends_on "md5sha1sum"
...
```


@justinsb @kris-nova @chrislovecnm When we release 1.5.2, can we do a "this is how we actually release" session so we can all learn how to make the changes in our repo stick elsewhere?

**Comment by jeremysf** [comment]
Hey gang, I'm running into this problem also. I'm on a brand new Macbook. Doing a `brew install md5sha1sum` didn't help (same error as above), but adding it into the dependency section with `brew edit kops` did the trick.

**Comment by michaelajr** [comment]
Same here. `brew install md5sha1sum` did not fix the the issue.

**Comment by michaelajr** [comment]
... but adding to the dependency section of the formula worked for us as well.

**Comment by tcf909** [comment]
Same here. brew edit kops + adding dependency line 'depends_on
"md5sha1sum"' worked for me as well.
