### ISSUE TITLE
Masters created with no Taints

### ISSUE THREAD

**Issue by braedon** [kubernetes/kops#2856]
Creating a new cluster using kops 1.6.2 produces masters with no taints, allowing normal pods to be scheduled on them.

Example cluster creation command:
```
kops create cluster \
      --channel alpha \
      --admin-access <redacted> \
      --master-size t2.medium \
      --master-zones ap-southeast-2a \
      --networking canal \
      --node-count 1 \
      --node-size m4.xlarge \
      --zones ap-southeast-2a \
      --image 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20161214 \
      --ssh-public-key ~/.ssh/test_id_rsa.pub \
      test.foo.com
```

**Comment by braedon** [comment]
No word on when this might be fixed? This is a fairly significant issue for us - we have to remember to apply the taints (and remove any pods that have been scheduled in the meantime) whenever we create or update a cluster. Is no-one else experiencing this issue?

**Comment by treacher** [comment]
Are you using Flanal or Canal? This may be related: https://github.com/coreos/flannel/issues/667

**Comment by treacher** [comment]
Issue has now been resolved here: https://github.com/projectcalico/canal/issues/77 it requires kops to update the version of the calico/node and calico/cni. I'm able to confirm the fix mentioned in the issue corrects the problem for me.

**Comment by braedon** [comment]
@treacher thanks, that looks like it could be it. I'll confirm it's fixed when I can move our cluster to that Canal version.

**Comment by blakebarnett** [comment]
@braedon are you still seeing this?  I just noticed it on one of our clusters after upgrading to k8s 1.7.9 with kops 1.7.1

**Comment by braedon** [comment]
@blakebarnett Just upgraded our cluster to 1.7 (finally), and still seeing the issue. Looks like it's still using the old v1.2.1 version of calico, not v1.3.0. Looks like we need to wait for 1.8? https://github.com/kubernetes/kops/pull/3142

**Comment by blakebarnett** [comment]
I believe this was actually a calico issue and has been resolved in recent releases.  Feel free to re-open if you are still seeing it.
